---
title: "Introduction"
questions:
- "Can people look up basic information about your lake(s)?"
objectives:
- "Investigate some lake pages on Wikipedia"
keypoints:
- "Many pages are missing or incomplete"
---

```{r echo=FALSE}
source("../bin/chunk-options.R")
```

Wikipedia is a primary source of lake information for many people. 

Lets look at information about a local lake [Elk Lake (British Columbia)](https://en.wikipedia.org/wiki/Elk_Lake_(British_Columbia)):

```{r eval=FALSE, echo=FALSE}
library(wikilake)
lake_wiki("Elk Lake (British Columbia)")
```

```{r message=FALSE, echo=FALSE, cache=TRUE}
library(wikilake)
library(dplyr)
library(tibble)

dt        <- lake_wiki("Elk Lake (British Columbia)")
dt <- janitor::clean_names(dt)
knitr::kable(dplyr::select(dt, -"basin_countries", 
                               -primary_inflows:-primary_outflows, 
                               -surface_area, 
                               -residence_time))
```

https://gist.github.com/jsta/e486f337be6d5bcdb3aeb1335959de52

## Explore some lake lists

## Explore some lake maps
